import type { Agent, Task } from "../types";

export const SIMULATION_START_TIME = 9 * 60; // 09:00
export const SIMULATION_END_TIME = 18 * 60; // 18:00

export const INITIAL_AGENTS: Record<string, Agent> = {
  ockham: {
    id: "ockham",
    name: "Оккам",
    role: "Backend Arch",
    avatar:
      "https://api.dicebear.com/7.x/bottts/svg?seed=ockham&backgroundColor=e2e8f0",
    color: "#38bdf8",
    status: "IDLE",
    stress: 0,
    traits: ["Гений", "Язвительный"],
    position: { x: 340, y: 490 },
    basePosition: { x: 340, y: 490 },
    currentTaskId: null,
    busyUntil: 0,
    specialization: "Backend, DB, API",
    temperament: "Высокомерный гений",
    catchphrase: "Не плоди сущности.",
    trigger: "Плохой код.",
  },
  christina: {
    id: "christina",
    name: "Кристина",
    role: "Frontend Lead",
    avatar:
      "https://api.dicebear.com/7.x/bottts/svg?seed=christina&backgroundColor=fca5a5",
    color: "#791909",
    status: "IDLE",
    stress: 0,
    traits: ["Перфекционист", "Эстет"],
    position: { x: 550, y: 500 },
    basePosition: { x: 550, y: 500 },
    currentTaskId: null,
    busyUntil: 0,
    specialization: "React, UI/UX",
    temperament: "Прагматик",
    catchphrase: "Это точная наука.",
    trigger: "Сломанная верстка.",
  },
  darius: {
    id: "darius",
    name: "Дариус",
    role: "DevOps",
    avatar:
      "https://api.dicebear.com/7.x/bottts/svg?seed=darius&backgroundColor=bbf7d0",
    color: "#10b981",
    status: "IDLE",
    stress: 0,
    traits: ["Флегматик", "Хацкер"],
    position: { x: 820, y: 300 },
    basePosition: { x: 820, y: 300 },
    currentTaskId: null,
    busyUntil: 0,
    specialization: "CI/CD, Security",
    temperament: "Спокойный как удав",
    catchphrase: "Я скрипт написал.",
    trigger: "Ручной деплой.",
  },
};
export const INITIAL_TASKS: Record<string, Task> = {
  "task-1": {
    id: "task-1",
    title: "Спроектировать схему БД",
    difficulty: "HARD",
    description:
      "Определить связи для новых сущностей в PostgreSQL, оптимизировать индексы.",
    tags: ["Бэкенд", "SQL", "Архитектура"],
    durationMins: 120,
    stressPenalty: 20,
    status: "TODO",
    assignedAgentId: null,
    progressMins: 0,
  },
  "task-2": {
    id: "task-2",
    title: "Настроить CI/CD пайплайн",
    difficulty: "MEDIUM",
    description:
      "Написать GitHub Actions для автоматической сборки и деплоя в k8s.",
    tags: ["DevOps", "Автоматизация", "YAML"],
    durationMins: 90,
    stressPenalty: 15,
    status: "TODO",
    assignedAgentId: null,
    progressMins: 0,
  },
  "task-3": {
    id: "task-3",
    title: "Рефакторинг UI-кита",
    difficulty: "MEDIUM",
    description:
      "Перевести старые компоненты на новые дизайн-токены, исправить отступы.",
    tags: ["Фронтенд", "CSS", "UI/UX"],
    durationMins: 60,
    stressPenalty: 10,
    status: "TODO",
    assignedAgentId: null,
    progressMins: 0,
  },
  "task-4": {
    id: "task-4",
    title: "Написать документацию API",
    difficulty: "EASY",
    description: "Обновить Swagger, описать новые эндпоинты для фронтенда.",
    tags: ["Бэкенд", "Документация"],
    durationMins: 30,
    stressPenalty: 5,
    status: "TODO",
    assignedAgentId: null,
    progressMins: 0,
  },
};
